name: Spring Boot Kafka CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Spring Boot App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build project using Maven inside base-domains folder
      - name: Build Application
        working-directory: ./base-domains/base-domains
        run: mvn clean package -DskipTests

      # Step 4: Upload JAR artifact for inspection
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: base-domain-jar
          path: ./base-domains/base-domains/target/*.jar

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simulate Deployment
        run: |
          echo "✅ Build successful!"
          echo "🚀 Simulating deployment stage..."
          echo "Your Spring Boot JAR is ready to deploy."
