name: Simple CI/CD Pipeline

# Trigger when code is pushed to main branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Spring Boot Project
    runs-on: ubuntu-latest   # uses GitHub's hosted runner

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java (required for Spring Boot)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build project using Maven (no tests)
      - name: Build Application
        run: mvn clean package -DskipTests

      # Step 4: Archive build artifact (optional)
      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar

  deploy:
    name: Deploy to Server (Simulated)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Stage
        run: |
          echo "✅ Build completed successfully."
          echo "🚀 Simulating deployment step..."
          echo "Your Spring Boot JAR would be deployed here."
